### ISSUE TITLE
DocumentBuilder 非线程安全

### ISSUE THREAD

**Issue by jacobwwang** [ihaolin/common#3]
类 me.hao0.common.xml.XmlReaders 静态变量 DocumentBuilder builder 非线程安全

**Comment by ihaolin** [comment]
你好，现在是造成了什么现象呢？

**Comment by JimmyLincole** [comment]
`me.hao0.common.exception.XmlException: Xmls create fail
  at me.hao0.common.xml.XmlReaders.create(XmlReaders.java:54)
  at me.hao0.common.xml.XmlReaders.create(XmlReaders.java:43)
  at me.hao0.wepay.core.Component.readResp(Component.java:67)
  at me.hao0.wepay.core.Component.toMap(Component.java:57)
  at me.hao0.wepay.core.Component.doPost(Component.java:32)
  at me.hao0.wepay.core.Orders.doQueryOrder(Orders.java:63)
  at me.hao0.wepay.core.Orders.queryByOutTradeNo(Orders.java:58)
Caused by: org.xml.sax.SAXException: FWK005 parse may not be called while parsing.
  at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
  at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
  at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
  at me.hao0.common.xml.XmlReaders.create(XmlReaders.java:52)
  ... 41 common frames omitted
`

多线程环境下，当前 DocumentBuilder 对象正在转换文档，此时再次请求转换文档，就抛出了上面的异常：FWK005 parse may not be called while parsing.

**Comment by jacobwwang** [comment]
```
me.hao0.common.exception.XmlException: Xmls create fail
  at me.hao0.common.xml.XmlReaders.create(XmlReaders.java:54)
  at me.hao0.common.xml.XmlReaders.create(XmlReaders.java:43)
  at me.hao0.wepay.core.Component.readResp(Component.java:67)
  at me.hao0.wepay.core.Component.toMap(Component.java:57)
  at me.hao0.wepay.core.Component.doPost(Component.java:32)
  at me.hao0.wepay.core.Orders.doQueryOrder(Orders.java:63)
  at me.hao0.wepay.core.Orders.queryByOutTradeNo(Orders.java:58)
Caused by: org.xml.sax.SAXException: FWK005 parse may not be called while parsing.
  at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
  at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
  at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
  at me.hao0.common.xml.XmlReaders.create(XmlReaders.java:52)
  ... 41 common frames omitted
```

多线程环境下，当前 DocumentBuilder 对象正在转换文档，此时再次请求转换文档，就抛出了上面的异常：FWK005 parse may not be called while parsing.

**Comment by ihaolin** [comment]
问题是，`DocumentBuilderImpl`中的`fSchemaValidationManager`和`fUnparsedEntityHandler`不是线程安全的
